In [1]:
# Import the libraries we'll use below.
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns  # for nicer plots
sns.set(style="darkgrid")  # default style

import tensorflow as tf
from tensorflow import keras
from keras import metrics
from sklearn.model_selection import train_test_split
tf.get_logger().setLevel('INFO')

import os
from os import listdir
from PIL import Image

2023-10-18 23:56:57.463164: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
df = pd.read_csv('KidneyImages/kidneyData.csv')

In [3]:
display(df)

Unnamed: 0       image_id  \
0               0  Tumor- (1044)   
1               1    Tumor- (83)   
2               2   Tumor- (580)   
3               3  Tumor- (1701)   
4               4  Tumor- (1220)   
...           ...            ...   
12441       12441   Cyst- (2522)   
12442       12442   Cyst- (2627)   
12443       12443    Cyst- (972)   
12444       12444   Cyst- (2323)   
12445       12445   Cyst- (2145)   

                                                    path   diag  target  Class  
0      /content/data/CT KIDNEY DATASET Normal, CYST, ...  Tumor       3  Tumor  
1      /content/data/CT KIDNEY DATASET Normal, CYST, ...  Tumor       3  Tumor  
2      /content/data/CT KIDNEY DATASET Normal, CYST, ...  Tumor       3  Tumor  
3      /content/data/CT KIDNEY DATASET Normal, CYST, ...  Tumor       3  Tumor  
4      /content/data/CT KIDNEY DATASET Normal, CYST, ...  Tumor       3  Tumor  
...                                                  ...    ...     ...    ...  
12441  /content/data/CT KIDNEY DATASET Normal, CYST, ...   Cyst       0   Cyst  
12442  /content/data/CT KIDNEY DATASET Normal, CYST, ...   Cyst       0   Cyst  
12443  /content/data/CT KIDNEY DATASET Normal, CYST, ...   Cyst       0   Cyst  
12444  /content/data/CT KIDNEY DATASET Normal, CYST, ...   Cyst       0   Cyst  
12445  /content/data/CT KIDNEY DATASET Normal, CYST, ...   Cyst       0   Cyst  

[12446 rows x 6 columns]

In [4]:
newsize = (256, 256)

In [5]:
## Read in all images
# First, read in all cyst images

cystImages = []

# Get the correct folder of images
folder_dir = "KidneyImages/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone/Cyst"


for images in os.listdir(folder_dir): # For each item in the folder
    if (images.endswith(".jpg")): # If it is a jpg
        image = Image.open(folder_dir + '/' + images) # Open the image
        image = image.resize(newsize) # Resize it to 256x256
        npImage = np.asarray(image) # Turn it into an array
        reshapedImage = npImage[:, :, 0] # Get rid of the last two color values (since it is black and white)
        cystImages.append({'image_id': images[:-4], 'image': reshapedImage}) # Add the information to the dictionary

In [6]:
# Then all normal images
normalImages = []

folder_dir = "KidneyImages/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone/Normal"


for images in os.listdir(folder_dir):
    if (images.endswith(".jpg")):
        image = Image.open(folder_dir + '/' + images)
        image = image.resize(newsize)
        npImage = np.asarray(image)
        reshapedImage = npImage[:, :, 0]

        normalImages.append({'image_id': images[:-4], 'image': reshapedImage})

In [7]:
# Then all stone images
stoneImages = []

folder_dir = "KidneyImages/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone/Stone"


for images in os.listdir(folder_dir):
    if (images.endswith(".jpg")):
        image = Image.open(folder_dir + '/' + images)
        image = image.resize(newsize)
        npImage = np.asarray(image)
        reshapedImage = npImage[:, :, 0]

        stoneImages.append({'image_id': images[:-4], 'image': reshapedImage})

In [8]:
# Then all tumor images
tumorImages = []

folder_dir = "KidneyImages/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone/Tumor"


for images in os.listdir(folder_dir):
    if (images.endswith(".jpg")):
        image = Image.open(folder_dir + '/' + images)
        image = image.resize(newsize)
        reshapedImage = npImage[:, :, 0]
        npImage = np.asarray(image)

        tumorImages.append({'image_id': images[:-4], 'image': reshapedImage})

In [9]:
# Concatenate all list of images, and turn into a data frame

allImages = cystImages + stoneImages + normalImages + tumorImages

imgs = pd.DataFrame(allImages)

In [10]:
imgs

image_id                                              image
0        Cyst- (630)  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
1        Cyst- (260)  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
2       Cyst- (1631)  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
3       Cyst- (1261)  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
4       Cyst- (1774)  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
...              ...                                                ...
12441   Tumor- (209)  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
12442  Tumor- (1390)  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
12443   Tumor- (659)  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
12444  Tumor- (1685)  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
12445  Tumor- (2103)  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...

[12446 rows x 2 columns]

In [11]:
# Make a dictionary of labels
labelDictionary = {0: 'Cyst', 1: 'Normal', 2: 'Stone', 3:'Tumor'}

In [12]:
# Merge with the other dataframe to get each image matched with its label
imgWithLabel = imgs.merge(df, how = 'inner', on = 'image_id')
imgWithLabel = imgWithLabel[['image', 'target']]

In [13]:
X = imgWithLabel['image'].to_numpy()
y = imgWithLabel['target'].to_numpy()

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [15]:
np.random.seed(0)
indices = np.arange(X_train.shape[0])
shuffled_indices = np.random.permutation(indices)
X_train = X_train[shuffled_indices]
y_train = y_train[shuffled_indices]

In [16]:
X_train

array([array([[0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              ...,
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
       array([[0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              ...,
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
       array([[0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              ...,
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0]], dtype=uint8), ...,
       array([[0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              [0, 0, 0, ..., 0, 0, 0],
              ...,
              [0, 0, 0, ..., 0, 0, 0],
              [0

In [21]:
def build_model(n_classes,   #should we change the n_classes to 4? since we only have 4 classes
                hidden_layer_sizes=[],
                activation='relu',
                optimizer='SGD',
                learning_rate=0.01):
    tf.keras.backend.clear_session()
    np.random.seed(0)
    tf.random.set_seed(0)
    model = tf.keras.models.Sequential()
    # Flatten the input shape
    model.add(tf.keras.layers.Flatten())
    # Add hidden layers
    for layer_size in hidden_layer_sizes:
        model.add(tf.keras.layers.Dense(layer_size, activation=activation))
    #Add the last neural network layer
    model.add(tf.keras.layers.Dense(units=n_classes, activation='softmax'))
    if optimizer == 'SGD':
        model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate),
                      loss='sparse_categorical_crossentropy',
                      metrics=['accuracy'])
    elif optimizer == 'Adam':
        model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                      loss='sparse_categorical_crossentropy',
                      metrics=['accuracy'])
    elif optimizer == 'RMSprop':
        model.compile(optimizer=tf.keras.optimizers.RMSprop(learning_rate=learning_rate),
                      loss='sparse_categorical_crossentropy',
                      metrics=['accuracy'])
    else:
        raise ValueError("Invalid optimizer. Please choose from ‘SGD’, ‘Adam’, or ‘RMSprop’.")
    return model


In [25]:
# Change the shape
X_train = np.array([np.asarray(x).flatten() for x in X_train]).astype(np.float32)
y_train = np.array([np.asarray(y) for y in y_train]).astype(np.float32)
X_test = np.array([np.asarray(x).flatten() for x in X_train]).astype(np.float32)
y_test = np.array([np.asarray(y) for y in y_train]).astype(np.float32)



# Build and compile the model
model = build_model(n_classes=4, hidden_layer_sizes=[128], activation='relu', optimizer='SGD', learning_rate=0.01)

# Train the model for 5 epochs
history = model.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.1, verbose=1)
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=2)




Epoch 1/5
140/140 [==============================] - 4s 28ms/step - loss: 186713.9062 - accuracy: 0.4056 - val_loss: 1.3416 - val_accuracy: 0.3855
Epoch 2/5
140/140 [==============================] - 4s 27ms/step - loss: 1.3193 - accuracy: 0.4110 - val_loss: 1.3206 - val_accuracy: 0.3855
Epoch 3/5
140/140 [==============================] - 4s 27ms/step - loss: 1.3005 - accuracy: 0.4110 - val_loss: 1.3109 - val_accuracy: 0.3855
Epoch 4/5
140/140 [==============================] - 4s 27ms/step - loss: 1.2908 - accuracy: 0.4110 - val_loss: 1.3065 - val_accuracy: 0.3855
Epoch 5/5
140/140 [==============================] - 4s 27ms/step - loss: 1.2858 - accuracy: 0.4110 - val_loss: 1.3044 - val_accuracy: 0.3855
312/312 - 2s - loss: 1.2861 - accuracy: 0.4085 - 2s/epoch - 6ms/step


In [26]:
model = build_model(n_classes=4, hidden_layer_sizes=[128], activation='relu', optimizer='RMSprop', learning_rate=0.01)

# Train the model for 5 epochs
history = model.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.1, verbose=1)
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=2)

Epoch 1/5
140/140 [==============================] - 5s 36ms/step - loss: 7473.9858 - accuracy: 0.6464 - val_loss: 2.0338 - val_accuracy: 0.5472
Epoch 2/5
140/140 [==============================] - 5s 35ms/step - loss: 8.0220 - accuracy: 0.5817 - val_loss: 1.0464 - val_accuracy: 0.5100
Epoch 3/5
140/140 [==============================] - 5s 36ms/step - loss: 1.7319 - accuracy: 0.5280 - val_loss: 1.1232 - val_accuracy: 0.5050
Epoch 4/5
140/140 [==============================] - 5s 36ms/step - loss: 1.1079 - accuracy: 0.5205 - val_loss: 1.1233 - val_accuracy: 0.5050
Epoch 5/5
140/140 [==============================] - 5s 37ms/step - loss: 1.1077 - accuracy: 0.5205 - val_loss: 1.1227 - val_accuracy: 0.5050
312/312 - 2s - loss: 1.1100 - accuracy: 0.5190 - 2s/epoch - 6ms/step


In [27]:
model = build_model(n_classes=4, hidden_layer_sizes=[128], activation='relu', optimizer='Adam', learning_rate=0.01)

# Train the model for 5 epochs
history = model.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.1, verbose=1)
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=2)

Epoch 1/5
140/140 [==============================] - 6s 43ms/step - loss: 1452.7842 - accuracy: 0.5614 - val_loss: 0.9824 - val_accuracy: 0.5994
Epoch 2/5
140/140 [==============================] - 6s 43ms/step - loss: 0.8948 - accuracy: 0.6442 - val_loss: 0.9066 - val_accuracy: 0.6245
Epoch 3/5
140/140 [==============================] - 6s 41ms/step - loss: 0.8717 - accuracy: 0.6613 - val_loss: 0.8876 - val_accuracy: 0.6325
Epoch 4/5
140/140 [==============================] - 6s 41ms/step - loss: 0.8711 - accuracy: 0.6536 - val_loss: 0.8465 - val_accuracy: 0.6456
Epoch 5/5
140/140 [==============================] - 6s 41ms/step - loss: 0.8307 - accuracy: 0.7048 - val_loss: 0.7474 - val_accuracy: 0.6988
312/312 - 2s - loss: 0.7713 - accuracy: 0.7094 - 2s/epoch - 6ms/step
